# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]
  schedule:
    - cron:  '1 1 1 * *'

name: R-CMD-check-hard

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # - {os: macos-latest,   r: 'release'}
          # - {os: windows-latest, r: 'release'}
         # - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
         # - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          # http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install MatrixExtra package
        run: |
          R -e 'cat("MatrixExtra Path: ", system.file(package = "MatrixExtra"), "\n"); getNamespaceExports("MatrixExtra")'
          R -e 'remove.packages("MatrixExtra")'
          R -e 'install.packages("remotes", dependencies = T); remotes::install_github("https://github.com/david-cortes/MatrixExtra")'
          R -e 'cat("MatrixExtra Path: ", system.file(package = "MatrixExtra"), "\n"); getNamespaceExports("MatrixExtra")'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: false
          extra-packages: any::rcmdcheck
          needs: check


      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          error-on: '"error"'
